import { Poppins } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/layouts/Navbar";
import Footer from "@/components/layouts/Footer";
import NextAuthProvider from "@/provider/NextAuthProvider";

const poppins = Poppins({
  weight: ["100", "200", "400", "500", "600", "800"],
});

export const fontBangla = localFont({
  src: "../fonts/mayaboti-normal.ttf",
});

// export const metadata = {
//   title: {
//     default: "Hero Kidz",
//     template: "%s | Hero Kidz"
//   },
//   description: "Generated by create next app",
// };

export const metadata = {
  metadataBase: new URL(
    "https://hero-kidz-kamrul-islam-96-kamruls-projects-a798478d.vercel.app/",
  ),
  title: {
    default: "Hero Kidz | Premium Kids Shop",
    template: "%s | Hero Kidz",
  },
  description:
    "High-quality toys, accessories, and gear for your little heroes. Shop the best collection online at Hero Kidz.",
  keywords: [
    "kids toys",
    "baby products",
    "Hero Kidz",
    "online toy shop Bangladesh",
  ],
  authors: [{ name: "Kamrul" }],
  creator: "Kamrul",
  publisher: "Hero Kidz",

  // Open Graph (Facebook, WhatsApp, LinkedIn)
  openGraph: {
    title: "Hero Kidz | Premium Kids Shop",
    description:
      "Quality toys for your little ones. Secure shopping & fast delivery!",
    url: "https://hero-kidz.vercel.app",
    siteName: "Hero Kidz",
    images: [
      {
        url: "/og-image.jpg",
        width: 1200,
        height: 630,
        alt: "Hero Kidz Shop Preview",
      },
    ],
    locale: "en_US",
    type: "website",
  },

  // Twitter (X)
  twitter: {
    card: "summary_large_image",
    title: "Hero Kidz | Best Kids Toys & Gear",
    description: "Quality toys for your little ones. Secure shopping!",
    images: ["/og-image.jpg"],
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <NextAuthProvider>
          <header className="py-4 md:w-11/12 mx-auto">
            <Navbar />
          </header>
          <main className="py-4 md:w-11/12 mx-auto min-h-[calc(100vh-318px)]">
            {children}
          </main>
          <footer>
            <Footer />
          </footer>
        </NextAuthProvider>
      </body>
    </html>
  );
}
